freeswitch : use latest debian:12.9-slim and fs release v1.10.12 & postgresql odbc
-------------------
for my ref. errors were

=========================
checking for speex >= 1.2rc1 speexdsp >= 1.2rc1... Package speex was not found in the pkg-config search path. Perhaps you should add the directory containing `speex.pc' to the PKG_CONFIG_PATH environment variable Package 'speex', required by 'virtual:world', not found
configure: error: Library requirements (speex >= 1.2rc1 speexdsp >= 1.2rc1) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them.

solution :  install     libspeex-dev
=========================
checking for libks2 >= 2.0.0... checking for libks >= 1.8.2... configure: error: You need to either install libks2 or libks or disable mod_verto in modules.conf

solution :  compile it from src
=========================
configure: error: You need to either install libedit-dev (>= 2.11) or configure with --disable-core-libedit-support

solution : installl libedit-dev
=========================
checking for signalwire_client2 >= 2.0.0... checking for signalwire_client >= 1.0.0... configure: error: You need to either install signalwire-client-c2 or signalwire-client-c or disable mod_signalwire in modules.conf

solution : compile it from source
=========================
Neither yasm nor nasm have been found. See the prerequisites section in the README for more info. Configuration failed.

solution :  install yasm
=========================
mod_lua.cpp:37:10: fatal error: lua.h: No such file or directory
   37 | #include "lua.h"

solution : install luarocks
=========================
freeswitch: error while loading shared libraries: libspandsp.so.3: cannot open shared object file: No such file or directory

Add /usr/local/lib to the linker path
=========================
fix freeswitch v.1.0.12 compilation

ref . : https://github.com/vishalk17/freeswitch/commit/fafc73802b4c0ef5dfddfc395363fbbcfb4b6c74

Resolve compilation errors in `mod_spandsp_dsp.c` caused by SpanDSP API updates:
1. Mode Constants : Updated deprecated mode names (e.g., `V18_MODE_5BIT_4545` → `V18_MODE_WEITBRECHT_5BIT_4545`).
2. v18_init Calls : Added missing `status_handler` and `status_handler_user_data` arguments (set to `NULL`).